### ISSUE TITLE
[BUG] Connector auth url mismatch - Hitachi HubSpot

### ISSUE THREAD

**Issue by NenadCrncec** [microsoft/PowerPlatformConnectors#3849]
### Type of Connector

Independent Publisher Connector

### Name of Connector

Hitachi HubSpot

### Describe the bug

when trying to connect to HubSpot error message appears:Couldn’t complete the connection
Authorization failed as the redirect URL 'https://global.consent.azure-apim.net/redirect/hubspotcrm' doesn't match the app's registered redirect URL. Please consult the app developer.

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 1 - Connector is broken or there's a very serious issue

### To Reproduce

use the connector to try to connect to HubSpot

### Expected behavior

that it works and there is no error

### Environment summary

Install Method Edge
CLI version N/A
OS version Mac OS

### Additional context

no additional context

**Comment by troystaylor** [comment]
Hello,
This has been fixed with the V2 version of the HubSpot connectors, which uses a HubSpot private app token to authenticate. The original connectors that use OAuth are not available for new connections.
@vmanoharas please close this issue once acknowledged.

Thanks,
Troy

**Comment by vmanoharas** [comment]
Thanks @troystaylor. 

Hi @NenadCrncec, please let me know if this issue is resolved, so that I will close this bug.

**Comment by NenadCrncec** [comment]
Hi
Well if the connector is obsolete, I assume that it should be removed. 
V2 connector is missing documentation and is not intuitive at all. 
I have solved my problem by using plain http request. 
So, bugs are still there, I just solved my problem in another way. 
Thansk ! 
👋

**Comment by troystaylor** [comment]
The connectors are not obsolete for those who have working OAuth connections. The V2 documentation can be found here: https://learn.microsoft.com/en-us/connectors/hubspotcrmv2/
